compiler:
  cpp:
    command: g++ -std=c++17 -O2 {src} -o {out}
    timeout: 30
system:
  default_memory_limit_mb: 256
  default_time_limit_ms: 1000
  judge_dir: judge
  max_file_size_mb: 10
  problems_dir: problems
web:
  debug: false                    # ✅ Disable debug mode
  host: 0.0.0.0                  # ✅ Accept external connections
  port: ${PORT:8000}             # ✅ Azure dynamic port or 8000 default
  secret_key: ${SECRET_KEY}      # ✅ Environment variable
ai:
  openai_api_key: ${OPENAI_API_KEY}  # ✅ Set via environment variable
  base_url: ${OPENAI_BASE_URL}  # ✅ Custom API endpoint (optional)
  model: ${OPENAI_MODEL}  # ✅ AI model to use (optional, defaults to gemini-2.5-flash)
  max_tokens: ${OPENAI_MAX_TOKENS}  # ✅ Token limit (optional, defaults to 6144)
  temperature: 0.7
  enabled: false  # Will be auto-enabled when API key is provided
