compiler:
  cpp:
    command: g++ -std=c++17 -O2 {src} -o {out}
    timeout: 30
system:
  default_memory_limit_mb: 256
  default_time_limit_ms: 1000
  judge_dir: judge
  max_file_size_mb: 10
  problems_dir: problems
web:
  debug: false                    # ✅ Disable debug mode
  host: 0.0.0.0                  # ✅ Accept external connections
  port: ${PORT:8000}             # ✅ Azure dynamic port or 8000 default
  secret_key: ${SECRET_KEY}      # ✅ Environment variable
